require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
-- require("core.plugin_config.tokyonight")
-- require("core.plugin_config.nightfox")
require("core.plugin_config.onedark")
-- require("core.plugin_config.material")
-- require("core.plugin_config.onenord")
-- require("core.plugin_config.catppucin")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_config")
require("core.plugin_config.fidget")
require("core.plugin_config.completions")
require("core.plugin_config.indent_blankline")
require("core.plugin_config.comment")
require("core.plugin_config.colorizer")
require("core.plugin_config.scrollbar")
require("core.plugin_config.neoscroll")
require("core.plugin_config.smoothcursor")
require("core.plugin_config.leap")
